### ISSUE TITLE
Can you make it so that I can attack custom NPCS and Mobs?

### ISSUE THREAD

**Issue by WGHaven** [CrystalDemo/CrystalDemo-Client#1]
Hello, I'm playing on a dragonblock c modpack, this features lots of different mobs and custom NPCs that I can face, I was wondering if there is a way to allow the mob aura to attack all of these? 
Thank you!

**Comment by CrystalDemo** [comment]
@WGHaven Can you link me the modpack?

**Comment by WGHaven** [comment]
@CrystalDemo http://www.technicpack.net/modpack/dbc-kia-1710.802726
That's the link to the modpack, thank you for looking into this for me!

**Comment by CrystalDemo** [comment]
@WGHaven Have you tested mob aura on dinosaurs?

**Comment by WGHaven** [comment]
Not specifically, but as far as I remember it does not work on them or any other mob that's not in the standard minecraft. It is mainly the custom boss NPCs that I am interested in. Thanks.

**Comment by CrystalDemo** [comment]
I tested a new code on dinosarus and works, so it's fixed. I release it tomorrow (i hope, i'm working on other features). If you have any other suggestions or if you find a bug let me know.

**Comment by WGHaven** [comment]
That's awesome man thanks I really appreciate it, I'll let you know if I have anymore suggestions. Also I think your Chest ESP doesn't always show an ESP around chests in some positions, just a little bug.

**Comment by CrystalDemo** [comment]
@WGHaven I released the new version, now on that custom mobs you have to use KillAura. Let me know if works fine.
