### ISSUE TITLE
SUGGESTIONS:

### ISSUE THREAD

**Issue by WGHaven** [CrystalDemo/CrystalDemo-Client#2]
Hello again haha, I have a few suggestions so its up to you whether or not you would like to add them.

No-Knockback
Anti-Blindness
I forgot the rest currently will update with more though

Also was wondering if on servers with no anticheat it is possible to clip through things or teleport?

**Comment by CrystalDemo** [comment]
All your requests can be added

**Comment by CrystalDemo** [comment]
@WGHaven [v2.3](https://github.com/CrystalDemo/CrystalDemo-Client/releases/tag/v2.3)
